### ISSUE TITLE
[AUTH] Config Client 설정

### ISSUE THREAD

**Issue by im-gnar** [sgs-ncns/NCNS-Server#19]
## 💫  Description

인증서버 config client 등록

## 🌈  Task List

- [x] bootstrap dependency, yml
- [x] jwt secretkey 주입받아서 교체

## 🌟  Consideration

bootstrap.yml
```
spring:
  cloud:
    config:
      uri: http://localhost:9020
```
